services:
  - type: web
    name: smart-bot-web
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python smart_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: BROTHER_USERNAME
        sync: false
      # RENDER_EXTERNAL_URL is auto-set by Render after the service is live.
